var GAME_LEVELS = [
  ["                                           x                                    ",
   "                                           x                                    ",
   "                                           x                                    ",
   "                                o o        x                                    ",
   "                               xxxxx       x                                    ",
   "                           o       x       x                         xxxxxxxxx  ",
   "    *         o     o     xx      x    xxxx  xxx        xxx                 x  ",
   "   xxxx       xxx   xxx            x    x     xvx        xvx                 x  ",
   "              x!!!!!!!x            x   !x                                    x  ",
   "              xxxxxxxxx xx  o      x    x                                    x  ",
   "                           xxx    xx    x                                    x  ",
   "                                   x    x                                    x  ",
   "xxxx                               x    x                                    x  ",
   "  x              o o               x    x                                 o  x  ",
   "  x             xxxx              xx!   x                           o     xxxx  ",
   "  x                                x                  o          xxxxx       x  ",
   "  x  @         x!!!! o        *    x  o         x  x  x  x  x  xxx!!!!!!!!!!!x  ",
   "  xxxxxx###xxxxxxxxxxxx   xx##xxxxxxxxxxxxxxxx!!x!!x!!x!!x!!x!!x xxxxxxxxxxxxx  ",
   "                      x!!!x                                                     ",
   "                      xxxxx                                                     ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
   ["                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "                      x                                               xnnnnnnn            x",
      "                      x                                               x                   x",
      " xxxxxxxxxxxxxxxxxxxxxx                              *                 x                   x",
      " xnnnnnn              x                         xx#xxxx#xx           x                o  x",
      " x                    x o   o    o              x         x  o        x                   x",
      " x                    x                         x         x           x               xx  x",
      " x                    xxxxx###xxxxx            x         x           x         xxxx      x",
      " x                    xnnnn                 xxxxx         xxxxxx      x            x      x",
      " x                                              x              x      xxxxxx       x      x",
      " x               *                              x              x      x         o  x      x",
      " x              xxxx                      xx      x              x      x            x      x",
      " x                         oo                   x              x      x        xxxxx      x",
      " x                                              x              x      x            x      x",
      " x                                              x              x      xxxx         x      x",
      " x     *                                        x              x  o      x  oo     x!!!!!!x",
      " x    xxxx           xxx       xxxxxx    xxxxx    x              x  o      x         x!!!!!!x",
      " x                           x    x!!!!x   x!!!!x              x  o      xxxxx     x!!!!!!x",
      " x                           x    x!!!!x   x!!!!x              x         x         x!!!!!!x",
      " x         ooo               x    x!!!!x   x!!!!x              xxxx      x       o x!!!!!!x",
      " x                           x    x!!!!x   x!!!!x              xy=     o x         x!!!!!!x",
      " x        xxxxxx      xxxxxxxx    x!!!!x   x!!!!x              x         x      xxxx!!!!!!x",
      " x        x    x!!!!!!x           x!!!!x   x!!!!x              x       xxx         x!!!!!!x",
      " x        x    x!!!!!!x           x!!!!x   x!!!!x              x                   x!!!!!!x",
      " x   @    x    x!!!!!!x           x!!!!x   x!!!!x              x                   x!!!!!!x",
      " xxxxxx   x    x!!!!!!x           x!!!!x   x!!!!x              x              xxx  x!!!!!!x",
      " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x              x              x!!!!!!!!!!!x",
      " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x              x              x!!!!!!!!!!!x",
      " x!!!!!!!!x    x!!!!!!x           x!!!!x   x!!!!x              x              x!!!!!!!!!!!x",
   " xxxxxxxxxx    xxxxxxxx           xxxxxxxxxxxxxxx              xxxxxxxxxxx####xxxxxxxxxxxxxxx"],
   ["                                                                                                                   ",
     "                                                                                                                   ",
     "                                                                                                                   ",
     "                                                                                                                   ",
     "                                                                                                                   ",
     "                                                                                                                   ",
     "                                                                                                                   ",
     "                             xxxxxxx                                                                               ",
     "                      xxx   xx!!!!!xx                                                                              ",
     "                             xx!!!xx   o     xxx                                                                   ",
     "          xxxx                xxvxx               xxx##xxx                                                          ",
     "xxx                                   xxx   !!!!!!xxxxxx                                                           ",
     "                                            !x!!!xxxxx                                                             ",
     "     o      *       o                       !xxxx                                                                  ",
     "                     x                      !xxxxx                *                                                 ",
     "    xxx    xxx     xxx      xx      xx      !xxx                           o                                       ",
     "      x!!!!!!!!!!!!x        xx      xx      !xxx                          xxx                                      ",
     "      xxxxxxxxxxxxxx        xx     xxx      !xxx          o          xxx        xxx                                ",
     "                            x       xx      !xxx               xxx                   xxx     o                     ",
     "                            x       xx      !xxxxx       xxxx                               xxxx                   ",
     "                            xxx    xxx      !xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxx                    ",
     "                            x       xx      ! xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                         ",
     "                                    xx      !                                                                      ",
     "                                  xxxx      !                                                                      ",
     "                                   xxx      !                                                                      ",
     "                     o             xxx      !                                                       xxxxx          ",
     "                        xxx  xxxxxxxxx      !                             *                          xxx           ",
     "  xx                xxx      xxxxxxxxx      !    o                       xxx              xxx      xxxxxxx  o  xx  ",
     "   x @         xxx           xxxxxxxxx      !            xxx                              <!x      xxxxxxx     x   ",
     "   xxxxxxxxxx                xxxxxxxxx      !   xxxx              xx             xx       x!x   xxxxxxxxxxxxxxxx   ",
     "!!!xxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!",
     "                                                                                                                   ",
  "                                                                                                                   "],
  ["                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "                                                                                                              ",
    "         x    x      xxx     x    x             x       x    xxx     yy    y    !                             ",
    "          x  x      x   x    x    x             x       x   x    x   y y   y    !                             ",
    "           x       x     x   x    x             x   x   x  x      x  y  y  y    !                             ",
    "           x        x   x    x    x             x  x x  x   x    x   y   y y    v                             ",
    "           x         xxx      xxxx x              x   x      yyyy    y    yy                                x  ",
    "  x                                                                                                          x  ",
    "  x                                                                                                          x  ",
    "  x  @                                          o                                                            x ",
    "  xxxxxxx                                     xxxxx       xx     xx     xxx                                  x ",
    "        x        o     o    o       *         x   x                     xxx           xxxxxxxxxxxxx     xxxxxx ",
    "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx###xxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
 "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
